// lib/pseo/types.ts — Re-export pSEO types for lib-layer usage
export type {
  PseoPageType,
  EntityType,
  EntityTag,
  TravelerPersona,
  Season,
  TravelStyle,
  ItineraryDuration,
  IntentCategory,
  IntentTemplate,
  LinkWeight,
  LinkRelationship,
  WeightedLink,
  PseoSeo,
  PseoPage,
  PseoFaq,
  PseoPageContent,
  CircuitHubContent,
  DestinationGuideContent,
  ItineraryContent,
  ComparisonContent,
  ActivityContent,
  SeasonalContent,
  PersonaContent,
  IntentContent,
  FaqHubContent,
  NearbyPlacesContent,
  CircuitDestinationEntry,
  SeasonInfo,
  BudgetRange,
  TransportInfo,
  ThingToDo,
  NearbyPlace,
  HotelSuggestion,
  ItineraryDay,
  ItineraryTimelineEntry,
  ItineraryHotel,
  ItineraryTransport,
  ComparisonEntry,
  ComparisonRow,
  ActivitySpot,
  IntentSection,
  CircuitSeed,
  DestinationSeed,
  ActivitySeed,
  EntitySeed,
  TravelTimeEntry,
  SeasonWeather,
} from '@/types/pseo';

export {
  PSEO_PAGE_TYPES,
  ENTITY_TYPES,
  TRAVELER_PERSONAS,
  SEASONS,
  TRAVEL_STYLES,
  ITINERARY_DURATIONS,
  INTENT_CATEGORIES,
  LINK_WEIGHTS,
  LINK_RELATIONSHIPS,
} from '@/types/pseo';
