// scripts/pseo/seeds/activities.ts — 25+ Uttarakhand travel activities
import type { ActivitySeed } from '@/types/pseo';

export const ACTIVITIES: ActivitySeed[] = [
  {
    name: 'White Water Rafting',
    slug: 'rafting',
    category: 'adventure',
    destinations: ['rishikesh', 'shivpuri', 'kaudiyala'],
    difficulty: 'Moderate to Challenging (Grade II–IV)',
    duration: '2–4 hours',
    best_seasons: ['autumn', 'summer'],
    description: 'Experience world-class white-water rafting on the Ganges with rapids ranging from Grade II to IV. The 16 km Shivpuri to Rishikesh stretch is the most popular, while the 36 km Kaudiyala stretch offers more extreme rapids like The Wall, Three Blind Mice, and Crossfire.',
    safety_notes: 'Always go with a certified operator. Life jackets are mandatory. Avoid during heavy monsoon (Jul–Aug) when rapids become dangerous.',
    cost_range: '₹600–2,500 per person',
  },
  {
    name: 'Bungee Jumping',
    slug: 'bungee-jumping',
    category: 'adventure',
    destinations: ['rishikesh'],
    difficulty: 'Extreme',
    duration: '15 minutes (activity), 2 hours (total experience)',
    best_seasons: ['autumn', 'winter', 'summer'],
    description: 'India\'s highest commercial bungee jump at 83 meters, operated by Jumpin Heights in Mohan Chatti near Rishikesh. The platform overlooks a rocky gorge with the river flowing below, offering an unparalleled adrenaline rush.',
    safety_notes: 'Minimum weight 40 kg, maximum 110 kg. Not recommended for those with heart conditions or spinal injuries. Advance booking required.',
    cost_range: '₹3,500–4,000 per person',
  },
  {
    name: 'Camping',
    slug: 'camping',
    category: 'adventure',
    destinations: ['shivpuri', 'rishikesh', 'chopta', 'kanatal', 'kedarkantha', 'dayara-bugyal'],
    difficulty: 'Easy to Moderate',
    duration: 'Overnight (1–2 nights)',
    best_seasons: ['autumn', 'winter', 'summer'],
    description: 'From riverside beach camps along the Ganges at Shivpuri to alpine meadow camps at Chopta and snow camps on the Kedarkantha trail, Uttarakhand offers camping experiences for every level. Most camps include bonfires, music, and adventure activities.',
    safety_notes: 'Carry warm layers even in summer at altitude. Ensure camp operator provides proper sleeping bags for winter camps.',
    cost_range: '₹800–5,000 per person per night',
  },
  {
    name: 'Yoga & Meditation',
    slug: 'yoga',
    category: 'wellness',
    destinations: ['rishikesh', 'haridwar'],
    difficulty: 'Easy',
    duration: '1 hour to multi-week courses',
    best_seasons: ['autumn', 'winter', 'summer'],
    description: 'Rishikesh is the Yoga Capital of the World, offering everything from drop-in sessions at riverside ashrams to 200-hour yoga teacher training certifications. Key centers include Parmarth Niketan, Sivananda Ashram, and the Beatles Ashram (Rajaji National Park).',
    safety_notes: 'Research ashrams carefully. Some require advance registration. Respect dress codes and ashram rules.',
    cost_range: '₹0 (free sessions) to ₹50,000+ (TTC courses)',
  },
  {
    name: 'Trekking',
    slug: 'trekking',
    category: 'adventure',
    destinations: ['kedarkantha', 'chopta', 'tungnath', 'dayara-bugyal', 'har-ki-dun', 'valley-of-flowers', 'auli'],
    difficulty: 'Easy to Difficult',
    duration: '1 day to 7 days',
    best_seasons: ['summer', 'autumn', 'winter'],
    description: 'Uttarakhand is India\'s trekking capital with trails for every level. From easy day treks like Tungnath–Chandrashila (3.5 km) to multi-day expeditions like Har Ki Dun (7 days) and the challenging Valley of Flowers trek, the state offers unmatched Himalayan trail variety.',
    safety_notes: 'Acclimatize properly above 3,000m. Carry rain gear and warm layers. Hire local guides for remote treks.',
    cost_range: '₹500 (day trek) to ₹15,000 (multi-day with guide)',
  },
  {
    name: 'Skiing',
    slug: 'skiing',
    category: 'adventure',
    destinations: ['auli'],
    difficulty: 'Moderate to Expert',
    duration: '1–7 days',
    best_seasons: ['winter', 'snowfall'],
    description: 'Auli is India\'s premier ski resort with professionally maintained slopes between 2,500m and 3,050m. The ski season runs from January to March with both natural and artificial snow. GMVN and ITBP offer skiing courses for beginners to advanced skiers.',
    safety_notes: 'Always ski with proper equipment and instruction. Beginners must take a multi-day course before skiing independently.',
    cost_range: '₹3,000–15,000 per day (including equipment and instructor)',
  },
  {
    name: 'Ganga Aarti',
    slug: 'ganga-aarti',
    category: 'spiritual',
    destinations: ['haridwar', 'rishikesh'],
    difficulty: 'Easy',
    duration: '1–2 hours (evening)',
    best_seasons: ['summer', 'monsoon', 'autumn', 'winter'],
    description: 'The magnificent Ganga Aarti is a daily fire ceremony performed at dusk on the banks of the Ganges. At Har Ki Pauri in Haridwar and Triveni Ghat in Rishikesh, hundreds of brass lamps illuminate the river as chants and bells fill the air in a deeply moving spiritual experience.',
    safety_notes: 'Arrive 30 minutes early for a good spot. Watch out for pickpockets in crowds. Respect the sacred atmosphere.',
    cost_range: 'Free',
  },
  {
    name: 'Temple Visits',
    slug: 'temple-visits',
    category: 'spiritual',
    destinations: ['haridwar', 'rishikesh', 'tungnath', 'triyuginarayan-temple', 'jageshwar', 'patal-bhuvaneshwar', 'joshimath', 'badrinath'],
    difficulty: 'Easy to Moderate (some require trekking)',
    duration: '1–4 hours per temple',
    best_seasons: ['summer', 'autumn', 'winter'],
    description: 'Uttarakhand is the Dev Bhoomi — Land of the Gods — with thousands of ancient temples. From the world\'s highest Shiva temple at Tungnath to the 124-temple complex at Jageshwar, and the mystical underground Patal Bhuvaneshwar cave, each temple offers a unique spiritual and architectural experience.',
    safety_notes: 'Some high-altitude temples close in winter. Check seasonal accessibility. Remove shoes before entering.',
    cost_range: 'Free (donations accepted)',
  },
  {
    name: 'Wildlife Safari',
    slug: 'wildlife-safari',
    category: 'nature',
    destinations: ['rajaji-national-park'],
    difficulty: 'Easy',
    duration: '3–4 hours',
    best_seasons: ['winter', 'summer'],
    description: 'Rajaji National Park, spanning 820 sq km near Haridwar and Rishikesh, is home to Asian elephants, Bengal tigers, leopards, and over 300 bird species. Jeep and elephant safaris offer incredible wildlife spotting opportunities in the Shivalik foothills.',
    safety_notes: 'Park is closed during monsoon season (Jun–Oct). Book safaris in advance. Follow park guide instructions strictly.',
    cost_range: '₹1,500–3,500 per person',
  },
  {
    name: 'Stargazing',
    slug: 'stargazing',
    category: 'nature',
    destinations: ['chopta', 'kanatal', 'mukteshwar', 'kausani', 'dayara-bugyal'],
    difficulty: 'Easy',
    duration: '2–4 hours (evening/night)',
    best_seasons: ['autumn', 'winter'],
    description: 'Uttarakhand\'s high-altitude destinations offer some of India\'s best stargazing opportunities with minimal light pollution. Chopta, Kanatal, and Mukteshwar on clear autumn and winter nights reveal the Milky Way, meteor showers, and thousands of visible stars.',
    safety_notes: 'Carry warm clothing. Use red-filter flashlights to preserve night vision. Best on moonless nights.',
    cost_range: 'Free (or ₹500–2,000 for guided sessions)',
  },
  {
    name: 'Photography Tours',
    slug: 'photography',
    category: 'nature',
    destinations: ['chopta', 'auli', 'kausani', 'munsiyari', 'valley-of-flowers', 'mussoorie'],
    difficulty: 'Easy to Moderate',
    duration: 'Half day to multi-day',
    best_seasons: ['autumn', 'winter', 'summer'],
    description: 'Uttarakhand\'s dramatic landscapes — from snow-capped peaks to alpine meadows, ancient temples to wildlife — make it a photographer\'s paradise. Golden hour at Kausani, rhododendron blooms at Chopta, and the Valley of Flowers in monsoon are legendary.',
    safety_notes: 'Protect equipment from moisture at altitude. Carry spare batteries in cold weather.',
    cost_range: '₹0 (self-guided) to ₹5,000 (guided photo walks)',
  },
  {
    name: 'Cliff Jumping',
    slug: 'cliff-jumping',
    category: 'adventure',
    destinations: ['rishikesh', 'shivpuri'],
    difficulty: 'Moderate to Extreme',
    duration: '1–2 hours',
    best_seasons: ['autumn', 'summer'],
    description: 'Jump from natural cliff faces into the deep pools of the Ganges near Rishikesh and Shivpuri. Heights range from 15 to 40 feet. Usually combined with rafting trips as a bonus activity.',
    safety_notes: 'Only jump at operator-approved spots. Water depth varies by season. Never jump alone.',
    cost_range: 'Included with rafting packages',
  },
  {
    name: 'Kayaking',
    slug: 'kayaking',
    category: 'adventure',
    destinations: ['rishikesh', 'shivpuri'],
    difficulty: 'Moderate',
    duration: '2–4 hours',
    best_seasons: ['autumn', 'summer'],
    description: 'Kayak through the rapids of the Ganges for a more intimate river experience than rafting. Instruction courses available from beginner to advanced levels at multiple Rishikesh operators.',
    safety_notes: 'Requires basic swimming ability. Helmets and PFDs mandatory.',
    cost_range: '₹1,500–4,000 per session',
  },
  {
    name: 'Paragliding',
    slug: 'paragliding',
    category: 'adventure',
    destinations: ['mussoorie'],
    difficulty: 'Easy (tandem)',
    duration: '15–30 minutes flight',
    best_seasons: ['autumn', 'summer'],
    description: 'Tandem paragliding flights over the Doon Valley from takeoff points near Mussoorie offer stunning aerial views of the Himalayan foothills and the sprawling valley below.',
    safety_notes: 'Only fly with certified pilots. Weather-dependent activity. Not recommended during monsoon.',
    cost_range: '₹2,500–4,000 per flight',
  },
  {
    name: 'Snow Trekking',
    slug: 'snow-trekking',
    category: 'adventure',
    destinations: ['kedarkantha', 'chopta', 'dayara-bugyal', 'auli', 'har-ki-dun'],
    difficulty: 'Moderate to Difficult',
    duration: '2–6 days',
    best_seasons: ['winter', 'snowfall'],
    description: 'Winter snow trekking is one of Uttarakhand\'s most magical experiences. Trails like Kedarkantha and Brahmatal offer 3–5 foot deep snow, frozen lakes, and summit views of the Greater Himalayan range glistening in winter sunlight.',
    safety_notes: 'Carry gaiters, microspikes, and proper layering. High-altitude sickness risk above 3,500m. Go with experienced guides.',
    cost_range: '₹5,000–15,000 per trek (with guide/operator)',
  },
  {
    name: 'Nature Walks',
    slug: 'nature-walks',
    category: 'nature',
    destinations: ['mussoorie', 'mukteshwar', 'binsar', 'kausani', 'kanatal'],
    difficulty: 'Easy',
    duration: '1–3 hours',
    best_seasons: ['summer', 'autumn', 'winter'],
    description: 'Gentle walks through deodar forests, orchid trails, and rhododendron groves are perfect for travelers who prefer slow, immersive nature experiences. Binsar Wildlife Sanctuary and Mukteshwar\'s IVRI campus are top picks.',
    safety_notes: 'Wear proper shoes. Watch for leeches during/after monsoon.',
    cost_range: '₹0–500 (guide optional)',
  },
  {
    name: 'Bird Watching',
    slug: 'bird-watching',
    category: 'nature',
    destinations: ['binsar', 'chopta', 'rajaji-national-park', 'mukteshwar', 'pangot'],
    difficulty: 'Easy',
    duration: '2–5 hours',
    best_seasons: ['autumn', 'winter', 'summer'],
    description: 'Uttarakhand is home to over 600 bird species. Binsar and Pangot are nationally recognized birding hotspots where you can spot Himalayan monals, koklass pheasants, and various raptors. Chopta\'s rhododendron forests attract rare high-altitude species.',
    safety_notes: 'Carry binoculars and a field guide. Early morning is best. Move quietly.',
    cost_range: '₹0 (self) to ₹2,000 (guided)',
  },
  {
    name: 'Sightseeing',
    slug: 'sightseeing',
    category: 'leisure',
    destinations: ['mussoorie', 'dehradun', 'haridwar', 'almora', 'ranikhet'],
    difficulty: 'Easy',
    duration: 'Half to full day',
    best_seasons: ['summer', 'autumn', 'winter'],
    description: 'Explore the colonial heritage, bustling bazaars, and panoramic viewpoints of Uttarakhand\'s most accessible towns. Mall Road in Mussoorie, Clock Tower in Dehradun, and Har Ki Pauri in Haridwar are essential sightseeing stops.',
    safety_notes: 'Popular spots get very crowded on weekends and holidays. Start early for a better experience.',
    cost_range: '₹0–1,000 (transport dependent)',
  },
  {
    name: 'Meditation',
    slug: 'meditation',
    category: 'wellness',
    destinations: ['rishikesh', 'haridwar'],
    difficulty: 'Easy',
    duration: '1 hour to multi-week retreats',
    best_seasons: ['autumn', 'winter', 'summer'],
    description: 'Find inner peace at Rishikesh\'s numerous meditation centers and ashrams. Vipassana retreats, guided mindfulness sessions, and Himalayan silence retreats offer transformative experiences on the banks of the Ganges.',
    safety_notes: 'Some retreats require silence vows and no electronics. Research the ashram before committing.',
    cost_range: '₹0 (donation-based) to ₹30,000 (luxury retreats)',
  },
  {
    name: 'Cave Exploration',
    slug: 'cave-exploration',
    category: 'adventure',
    destinations: ['robbers-cave', 'patal-bhuvaneshwar'],
    difficulty: 'Easy to Moderate',
    duration: '1–2 hours',
    best_seasons: ['summer', 'autumn', 'winter'],
    description: 'Explore natural limestone caves and underground formations. Robber\'s Cave near Dehradun features a river disappearing into rock, while Patal Bhuvaneshwar in Kumaon is a legendary underground temple cave with ancient rock formations.',
    safety_notes: 'Wear non-slip shoes. Patal Bhuvaneshwar requires descending narrow steps — not for claustrophobic visitors.',
    cost_range: '₹35–150 (entry fees)',
  },
];
