// scripts/pseo/seeds/destinations.ts — 35+ Uttarakhand destinations with full geographic data
import type { DestinationSeed } from '@/types/pseo';

export const DESTINATIONS: DestinationSeed[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // RISHIKESH CIRCUIT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Rishikesh',
    slug: 'rishikesh',
    circuit: 'rishikesh-circuit',
    district: 'Dehradun',
    coords: { lat: 30.0869, lng: 78.2676 },
    altitude_m: 372,
    description: 'Known as the Yoga Capital of the World, Rishikesh is a vibrant town on the banks of the Ganges, blending spiritual heritage with adrenaline-pumping adventure sports. From ancient ashrams and evening aarti ceremonies to white-water rafting and bungee jumping, Rishikesh offers an unmatched travel experience.',
    why_visit: [
      'World-class white-water rafting on the Ganges',
      'Yoga and meditation at centuries-old ashrams',
      'Bungee jumping from India\'s highest commercial platform',
      'Iconic Lakshman Jhula and Ram Jhula suspension bridges',
      'Vibrant cafés and backpacker culture along the riverfront',
    ],
    image: '/images/pseo/destinations/rishikesh.jpg',
    best_months: 'September to November, February to May',
    from_delhi: { distance_km: 240, drive_hours: 5.5, bus: true, train_to: 'Haridwar' },
    from_dehradun: { distance_km: 43, drive_hours: 1 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (35 km)',
    nearest_railway: 'Haridwar Junction (24 km)',
    travel_times: [
      { to: 'shivpuri', km: 16, hours: 0.5 },
      { to: 'kaudiyala', km: 35, hours: 1 },
      { to: 'mohanchatti', km: 10, hours: 0.3 },
      { to: 'neer-garh-waterfall', km: 5, hours: 0.2 },
      { to: 'beatles-ashram', km: 2, hours: 0.1 },
      { to: 'triveni-ghat', km: 3, hours: 0.1 },
      { to: 'kunjapuri-temple', km: 25, hours: 0.75 },
      { to: 'haridwar', km: 24, hours: 0.5 },
      { to: 'dehradun', km: 43, hours: 1 },
      { to: 'mussoorie', km: 75, hours: 2 },
    ],
    activities: ['rafting', 'bungee-jumping', 'camping', 'yoga', 'meditation', 'cliff-jumping', 'kayaking', 'trekking'],
    attractions: ['lakshman-jhula', 'ram-jhula', 'triveni-ghat', 'beatles-ashram', 'parmarth-niketan', 'neer-garh-waterfall'],
    accommodation: { budget: '₹500–1,500/night (hostels, dharamshalas)', mid: '₹1,500–4,000/night (riverside hotels)', luxury: '₹5,000–15,000/night (luxury resorts)' },
    weather: [
      { season: 'summer', months: 'Apr–Jun', temp_min: 25, temp_max: 40, rainfall: 'Low', road_conditions: 'Good', crowd_level: 'high', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 22, temp_max: 35, rainfall: 'Heavy', road_conditions: 'Landslide risk', crowd_level: 'low', accessible: true },
      { season: 'autumn', months: 'Oct–Nov', temp_min: 15, temp_max: 30, rainfall: 'None', road_conditions: 'Excellent', crowd_level: 'medium', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: 7, temp_max: 22, rainfall: 'None', road_conditions: 'Good', crowd_level: 'medium', accessible: true },
    ],
  },
  {
    name: 'Shivpuri',
    slug: 'shivpuri',
    circuit: 'rishikesh-circuit',
    district: 'Tehri Garhwal',
    coords: { lat: 30.1400, lng: 78.3800 },
    altitude_m: 380,
    description: 'Shivpuri is the rafting basecamp of Rishikesh, situated 16 km upstream where the Ganges rapids are at their most thrilling. Riverside camping under the stars with bonfire sessions is the quintessential Shivpuri experience.',
    why_visit: [
      'Starting point for 16 km and 24 km rafting stretches',
      'Beachside camping with bonfire and music',
      'Body surfing and cliff jumping spots',
      'Quieter alternative to main Rishikesh town',
    ],
    image: '/images/pseo/destinations/shivpuri.jpg',
    best_months: 'September to November, March to May',
    from_delhi: { distance_km: 256, drive_hours: 6, bus: true, train_to: 'Haridwar' },
    from_dehradun: { distance_km: 55, drive_hours: 1.5 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (50 km)',
    nearest_railway: 'Haridwar Junction (40 km)',
    travel_times: [
      { to: 'rishikesh', km: 16, hours: 0.5 },
      { to: 'kaudiyala', km: 20, hours: 0.5 },
      { to: 'mohanchatti', km: 8, hours: 0.25 },
    ],
    activities: ['rafting', 'camping', 'cliff-jumping', 'kayaking', 'body-surfing'],
    attractions: ['shivpuri-beach', 'ganges-rapids'],
    accommodation: { budget: '₹800–1,500/night (camp tents)', mid: '₹1,500–3,500/night (luxury camps)', luxury: '₹4,000–8,000/night (riverside resorts)' },
    weather: [
      { season: 'summer', months: 'Apr–Jun', temp_min: 25, temp_max: 40, rainfall: 'Low', road_conditions: 'Good', crowd_level: 'high', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 22, temp_max: 35, rainfall: 'Heavy', road_conditions: 'Fair', crowd_level: 'low', accessible: true },
      { season: 'autumn', months: 'Oct–Nov', temp_min: 15, temp_max: 30, rainfall: 'None', road_conditions: 'Excellent', crowd_level: 'high', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: 7, temp_max: 22, rainfall: 'None', road_conditions: 'Good', crowd_level: 'medium', accessible: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DEHRADUN CIRCUIT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Mussoorie',
    slug: 'mussoorie',
    circuit: 'dehradun-circuit',
    district: 'Dehradun',
    coords: { lat: 30.4598, lng: 78.0644 },
    altitude_m: 2005,
    description: 'The Queen of Hills, Mussoorie is a charming colonial-era hill station perched at 2,005m above sea level. With sweeping views of the Doon Valley and the snow-clad Himalayan ranges, this beloved destination offers Mall Road strolls, Kempty Falls, and the breathtaking George Everest viewpoint.',
    why_visit: [
      'Panoramic Himalayan views from George Everest Peak',
      'Colonial charm of Mall Road and Camel\'s Back Road',
      'Kempty Falls — the most popular waterfall in Uttarakhand',
      'Pleasant weather year-round as a classic hill station escape',
      'Gateway to offbeat Chakrata and Kanatal',
    ],
    image: '/images/pseo/destinations/mussoorie.jpg',
    best_months: 'March to June, September to November',
    from_delhi: { distance_km: 290, drive_hours: 6.5, bus: true, train_to: 'Dehradun' },
    from_dehradun: { distance_km: 35, drive_hours: 1 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (60 km)',
    nearest_railway: 'Dehradun Railway Station (35 km)',
    travel_times: [
      { to: 'dehradun', km: 35, hours: 1 },
      { to: 'george-everest', km: 6, hours: 0.25 },
      { to: 'kanatal', km: 78, hours: 2.5 },
      { to: 'chakrata', km: 90, hours: 3 },
      { to: 'rishikesh', km: 75, hours: 2 },
    ],
    activities: ['sightseeing', 'nature-walks', 'photography', 'cable-car', 'shopping', 'trekking'],
    attractions: ['mall-road', 'kempty-falls', 'george-everest', 'camels-back-road', 'gun-hill', 'cloud-end'],
    accommodation: { budget: '₹800–2,000/night (guesthouses)', mid: '₹2,000–5,000/night (heritage hotels)', luxury: '₹6,000–20,000/night (Jaypee, ITC)' },
    weather: [
      { season: 'summer', months: 'Apr–Jun', temp_min: 15, temp_max: 30, rainfall: 'Low', road_conditions: 'Good', crowd_level: 'high', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 14, temp_max: 25, rainfall: 'Heavy', road_conditions: 'Landslide risk', crowd_level: 'low', accessible: true },
      { season: 'autumn', months: 'Oct–Nov', temp_min: 8, temp_max: 22, rainfall: 'None', road_conditions: 'Excellent', crowd_level: 'medium', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: 1, temp_max: 14, rainfall: 'Occasional snow', road_conditions: 'Cold but open', crowd_level: 'medium', accessible: true },
    ],
  },
  {
    name: 'Kanatal',
    slug: 'kanatal',
    circuit: 'dehradun-circuit',
    district: 'Tehri Garhwal',
    coords: { lat: 30.4000, lng: 78.3200 },
    altitude_m: 2590,
    description: 'Kanatal is an offbeat hill station at 2,590m, offering serene forests, adventure camping, and stunning Himalayan panoramas without the tourist crowds. The nearby Surkanda Devi Temple and Kodia Jungle make it perfect for nature lovers and couples seeking solitude.',
    why_visit: [
      'Offbeat and crowd-free hill retreat',
      'Apple orchards and dense deodar forests',
      'Adventure camps with zip-lining and rappelling',
      'Surkanda Devi Temple with 360° Himalayan views',
    ],
    image: '/images/pseo/destinations/kanatal.jpg',
    best_months: 'March to June, September to November',
    from_delhi: { distance_km: 312, drive_hours: 8, bus: true, train_to: 'Dehradun' },
    from_dehradun: { distance_km: 78, drive_hours: 2.5 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (85 km)',
    nearest_railway: 'Dehradun Railway Station (78 km)',
    travel_times: [
      { to: 'mussoorie', km: 78, hours: 2.5 },
      { to: 'dehradun', km: 78, hours: 2.5 },
      { to: 'chopta', km: 180, hours: 6 },
    ],
    activities: ['camping', 'trekking', 'stargazing', 'photography', 'rappelling', 'zip-lining'],
    attractions: ['surkanda-devi-temple', 'kodia-jungle', 'tehri-dam-viewpoint'],
    accommodation: { budget: '₹800–1,500/night (camps)', mid: '₹2,000–4,000/night (cottages)', luxury: '₹5,000–12,000/night (luxury camps)' },
    weather: [
      { season: 'summer', months: 'Apr–Jun', temp_min: 12, temp_max: 25, rainfall: 'Low', road_conditions: 'Good', crowd_level: 'medium', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 12, temp_max: 20, rainfall: 'Heavy', road_conditions: 'Risky', crowd_level: 'low', accessible: true },
      { season: 'autumn', months: 'Oct–Nov', temp_min: 5, temp_max: 18, rainfall: 'None', road_conditions: 'Excellent', crowd_level: 'low', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: -2, temp_max: 10, rainfall: 'Snowfall', road_conditions: 'Snow possible', crowd_level: 'medium', accessible: true },
      { season: 'snowfall', months: 'Dec–Feb', temp_min: -5, temp_max: 5, rainfall: 'Heavy snow', road_conditions: 'Chains needed', crowd_level: 'medium', accessible: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // HARIDWAR CIRCUIT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Haridwar',
    slug: 'haridwar',
    circuit: 'haridwar-circuit',
    district: 'Haridwar',
    coords: { lat: 29.9457, lng: 78.1642 },
    altitude_m: 314,
    description: 'One of the seven holiest places in Hinduism, Haridwar is where the Ganges leaves the mountains and enters the plains. The spectacular Ganga Aarti at Har Ki Pauri draws thousands every evening, making it a profoundly spiritual and visually stunning destination.',
    why_visit: [
      'Mesmerizing Ganga Aarti at Har Ki Pauri every evening',
      'One of India\'s seven holiest pilgrimage cities',
      'Gateway to Char Dham yatra',
      'Ancient temples and ashrams along the Ganges',
      'Rajaji National Park for wildlife safaris',
    ],
    image: '/images/pseo/destinations/haridwar.jpg',
    best_months: 'October to March',
    from_delhi: { distance_km: 215, drive_hours: 5, bus: true, train_to: 'Haridwar' },
    from_dehradun: { distance_km: 52, drive_hours: 1.5 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (38 km)',
    nearest_railway: 'Haridwar Junction (0 km)',
    travel_times: [
      { to: 'rishikesh', km: 24, hours: 0.5 },
      { to: 'rajaji-national-park', km: 10, hours: 0.25 },
      { to: 'dehradun', km: 52, hours: 1.5 },
    ],
    activities: ['ganga-aarti', 'temple-visits', 'wildlife-safari', 'river-bathing', 'spiritual-walks', 'yoga'],
    attractions: ['har-ki-pauri', 'mansa-devi-temple', 'chandi-devi-temple', 'saptrishi-ashram', 'daksh-mahadev-temple'],
    accommodation: { budget: '₹400–1,200/night (dharamshalas)', mid: '₹1,200–3,500/night (hotels)', luxury: '₹4,000–10,000/night (resort hotels)' },
    weather: [
      { season: 'summer', months: 'Apr–Jun', temp_min: 25, temp_max: 42, rainfall: 'Low', road_conditions: 'Good', crowd_level: 'high', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 24, temp_max: 36, rainfall: 'Heavy', road_conditions: 'Fair', crowd_level: 'medium', accessible: true },
      { season: 'autumn', months: 'Oct–Nov', temp_min: 15, temp_max: 32, rainfall: 'None', road_conditions: 'Excellent', crowd_level: 'medium', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: 5, temp_max: 22, rainfall: 'None', road_conditions: 'Good', crowd_level: 'medium', accessible: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CHOPTA / RUDRAPRAYAG CIRCUIT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Chopta',
    slug: 'chopta',
    circuit: 'chopta-circuit',
    district: 'Rudraprayag',
    coords: { lat: 30.4916, lng: 79.2168 },
    altitude_m: 2680,
    description: 'Chopta, the Mini Switzerland of Uttarakhand, is a pristine hamlet surrounded by forests of pine, deodar, and rhododendron at 2,680m. It is the base camp for the Tungnath–Chandrashila trek, offering views of the majestic Himalayan peaks including Trishul, Nanda Devi, and Chaukhamba.',
    why_visit: [
      'Base camp for Tungnath — the highest Shiva temple in the world',
      'Chandrashila summit with 360° Himalayan panorama',
      'Pristine alpine meadows (bugyals) and rhododendron forests',
      'Deoria Tal — a stunning high-altitude lake reflecting the Chaukhamba peaks',
      'Significantly less crowded than mainstream hill stations',
    ],
    image: '/images/pseo/destinations/chopta.jpg',
    best_months: 'April to June, September to November',
    from_delhi: { distance_km: 430, drive_hours: 10, bus: true, train_to: 'Haridwar' },
    from_dehradun: { distance_km: 225, drive_hours: 7 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (226 km)',
    nearest_railway: 'Rishikesh Railway Station (202 km)',
    travel_times: [
      { to: 'tungnath', km: 3.5, hours: 2.5 },
      { to: 'kartik-swami', km: 30, hours: 1.5 },
      { to: 'deoria-tal', km: 25, hours: 1 },
      { to: 'triyuginarayan-temple', km: 55, hours: 2 },
      { to: 'dhari-devi-temple', km: 80, hours: 3 },
      { to: 'rishikesh', km: 202, hours: 6.5 },
    ],
    activities: ['trekking', 'meadow-camping', 'photography', 'bird-watching', 'stargazing', 'snow-trekking'],
    attractions: ['tungnath-temple', 'chandrashila-peak', 'deoria-tal', 'rohini-bugyal'],
    accommodation: { budget: '₹500–1,200/night (basic lodges)', mid: '₹1,200–3,000/night (eco camps)', luxury: '₹3,500–7,000/night (boutique stays)' },
    weather: [
      { season: 'summer', months: 'Apr–Jun', temp_min: 8, temp_max: 20, rainfall: 'Moderate', road_conditions: 'Good', crowd_level: 'medium', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 8, temp_max: 15, rainfall: 'Very heavy', road_conditions: 'Dangerous', crowd_level: 'low', accessible: false },
      { season: 'autumn', months: 'Oct–Nov', temp_min: 2, temp_max: 15, rainfall: 'None', road_conditions: 'Excellent', crowd_level: 'medium', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: -5, temp_max: 8, rainfall: 'Heavy snowfall', road_conditions: 'Snow-covered', crowd_level: 'medium', accessible: true },
      { season: 'snowfall', months: 'Dec–Feb', temp_min: -10, temp_max: 2, rainfall: '2–4 ft snow', road_conditions: 'Difficult', crowd_level: 'high', accessible: true },
    ],
  },
  {
    name: 'Tungnath',
    slug: 'tungnath',
    circuit: 'chopta-circuit',
    district: 'Rudraprayag',
    coords: { lat: 30.4899, lng: 79.2193 },
    altitude_m: 3680,
    description: 'Tungnath is the highest Shiva temple in the world at 3,680m, part of the Panch Kedar pilgrimage circuit. The 3.5 km trek from Chopta passes through dense rhododendron forests and alpine meadows, culminating at this ancient stone temple with breathtaking views.',
    why_visit: [
      'Highest Shiva temple in the world (3,680m)',
      'Part of the sacred Panch Kedar pilgrimage',
      'Stunning 3.5 km trek through rhododendron forests',
      'Gateway to Chandrashila summit (4,000m)',
    ],
    image: '/images/pseo/destinations/tungnath.jpg',
    best_months: 'April to June, September to November',
    from_delhi: { distance_km: 434, drive_hours: 10.5, bus: true, train_to: 'Haridwar' },
    from_dehradun: { distance_km: 228, drive_hours: 7.5 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (230 km)',
    nearest_railway: 'Rishikesh Railway Station (205 km)',
    travel_times: [
      { to: 'chopta', km: 3.5, hours: 2.5 },
      { to: 'chandrashila', km: 1.5, hours: 1 },
    ],
    activities: ['trekking', 'temple-visits', 'photography', 'snow-trekking'],
    attractions: ['tungnath-temple', 'chandrashila-peak'],
    accommodation: { budget: '₹0 (temple shelter)', mid: '₹500–1,000/night (basic at Chopta)', luxury: 'N/A — stay at Chopta' },
    weather: [
      { season: 'summer', months: 'Apr–Jun', temp_min: 3, temp_max: 15, rainfall: 'Moderate', road_conditions: 'Trek only', crowd_level: 'medium', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 5, temp_max: 10, rainfall: 'Very heavy', road_conditions: 'Dangerous', crowd_level: 'low', accessible: false },
      { season: 'autumn', months: 'Oct–Nov', temp_min: -2, temp_max: 10, rainfall: 'None', road_conditions: 'Good', crowd_level: 'medium', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: -15, temp_max: 0, rainfall: 'Buried in snow', road_conditions: 'Closed', crowd_level: 'low', accessible: false },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // JOSHIMATH / AULI CIRCUIT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Auli',
    slug: 'auli',
    circuit: 'joshimath-auli-circuit',
    district: 'Chamoli',
    coords: { lat: 30.5302, lng: 79.5666 },
    altitude_m: 2800,
    description: 'Auli is India\'s premier skiing destination, perched at 2,800m with panoramic views of Nanda Devi (7,816m), Kamet, and Mana Parvat. In winter, its slopes transform into a skiing paradise; in summer, vast apple orchards and alpine meadows make it a tranquil mountain retreat.',
    why_visit: [
      'India\'s best skiing destination with professional slopes',
      'Panoramic views of Nanda Devi and Himalayan peaks',
      'Asia\'s longest cable car (gondola) from Joshimath',
      'Artificial lake at 2,500m — one of the highest in the world',
      'Gateway to Valley of Flowers in summer',
    ],
    image: '/images/pseo/destinations/auli.jpg',
    best_months: 'November to March (skiing), May to June (summer)',
    from_delhi: { distance_km: 500, drive_hours: 12, bus: true, train_to: 'Haridwar' },
    from_dehradun: { distance_km: 290, drive_hours: 9 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (295 km)',
    nearest_railway: 'Haridwar Junction (277 km)',
    travel_times: [
      { to: 'joshimath', km: 16, hours: 0.5 },
      { to: 'valley-of-flowers', km: 35, hours: 6 },
      { to: 'badrinath', km: 60, hours: 2 },
      { to: 'mana-village', km: 65, hours: 2.5 },
    ],
    activities: ['skiing', 'cable-car', 'trekking', 'photography', 'snow-activities', 'meadow-walks'],
    attractions: ['auli-ski-slopes', 'auli-artificial-lake', 'gorson-bugyal', 'nanda-devi-viewpoint'],
    accommodation: { budget: '₹1,000–2,000/night (GMVN guesthouse)', mid: '₹2,500–5,000/night (hotels)', luxury: '₹6,000–15,000/night (Cliff Top Club)' },
    weather: [
      { season: 'summer', months: 'May–Jun', temp_min: 5, temp_max: 20, rainfall: 'Low', road_conditions: 'Good', crowd_level: 'medium', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 5, temp_max: 15, rainfall: 'Heavy', road_conditions: 'Landslides', crowd_level: 'low', accessible: false },
      { season: 'winter', months: 'Nov–Mar', temp_min: -8, temp_max: 5, rainfall: '3–6 ft snowfall', road_conditions: 'Snow-covered', crowd_level: 'high', accessible: true },
      { season: 'snowfall', months: 'Dec–Feb', temp_min: -12, temp_max: 0, rainfall: 'Heavy snow', road_conditions: 'Ski-ready', crowd_level: 'high', accessible: true },
    ],
  },
  {
    name: 'Joshimath',
    slug: 'joshimath',
    circuit: 'joshimath-auli-circuit',
    district: 'Chamoli',
    coords: { lat: 30.5551, lng: 79.5663 },
    altitude_m: 1890,
    description: 'Joshimath is a sacred town and one of the four cardinal mathas (monasteries) established by Adi Shankaracharya. It serves as the winter seat of Lord Badri and the gateway to Auli, Valley of Flowers, Hemkund Sahib, and Badrinath.',
    why_visit: [
      'One of four Shankaracharya mathas in India',
      'Gateway to Auli, Valley of Flowers, and Badrinath',
      'Narsingh Temple with the sacred diminishing idol',
      'Base for multiple high-altitude treks',
    ],
    image: '/images/pseo/destinations/joshimath.jpg',
    best_months: 'May to June, September to November',
    from_delhi: { distance_km: 490, drive_hours: 11.5, bus: true, train_to: 'Haridwar' },
    from_dehradun: { distance_km: 275, drive_hours: 8.5 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (280 km)',
    nearest_railway: 'Haridwar Junction (262 km)',
    travel_times: [
      { to: 'auli', km: 16, hours: 0.5 },
      { to: 'badrinath', km: 44, hours: 1.5 },
      { to: 'valley-of-flowers', km: 21, hours: 5.5 },
      { to: 'hemkund-sahib', km: 23, hours: 7 },
      { to: 'mana-village', km: 48, hours: 2 },
    ],
    activities: ['temple-visits', 'trekking', 'cable-car', 'pilgrimage', 'photography'],
    attractions: ['narsingh-temple', 'shankaracharya-math', 'vasundhara-falls', 'tapovan'],
    accommodation: { budget: '₹500–1,500/night (dharamshalas)', mid: '₹1,500–3,500/night (hotels)', luxury: '₹4,000–8,000/night (GMVN)' },
    weather: [
      { season: 'summer', months: 'May–Jun', temp_min: 10, temp_max: 25, rainfall: 'Low', road_conditions: 'Good', crowd_level: 'high', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 12, temp_max: 20, rainfall: 'Very heavy', road_conditions: 'Dangerous', crowd_level: 'low', accessible: false },
      { season: 'autumn', months: 'Oct–Nov', temp_min: 5, temp_max: 18, rainfall: 'None', road_conditions: 'Good', crowd_level: 'medium', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: -5, temp_max: 10, rainfall: 'Snowfall', road_conditions: 'Snow-possible', crowd_level: 'low', accessible: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UTTARKASHI CIRCUIT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Kedarkantha',
    slug: 'kedarkantha',
    circuit: 'uttarkashi-circuit',
    district: 'Uttarkashi',
    coords: { lat: 31.0700, lng: 78.1700 },
    altitude_m: 3810,
    description: 'Kedarkantha (12,500 ft) is one of India\'s most popular winter treks, known for its pristine snow trails, dense pine forests, and a breathtaking summit with 360° views of the Himalayan range including Swargarohini, Bandarpoonch, and Black Peak.',
    why_visit: [
      'Best winter trek in India — doable by beginners',
      '360° summit views of Swargarohini, Bandarpoonch, Black Peak',
      'Snow-covered trails through pine and oak forests',
      'Base village of Sankri is a charming Himalayan hamlet',
    ],
    image: '/images/pseo/destinations/kedarkantha.jpg',
    best_months: 'December to April (snow), May to June (green)',
    from_delhi: { distance_km: 480, drive_hours: 11, bus: true, train_to: 'Dehradun' },
    from_dehradun: { distance_km: 210, drive_hours: 8 },
    nearest_airport: 'Jolly Grant Airport, Dehradun (215 km)',
    nearest_railway: 'Dehradun Railway Station (210 km)',
    travel_times: [
      { to: 'harshil', km: 95, hours: 4 },
      { to: 'dayara-bugyal', km: 50, hours: 2.5 },
      { to: 'uttarkashi', km: 150, hours: 5 },
    ],
    activities: ['high-altitude-trekking', 'snow-trekking', 'camping', 'photography'],
    attractions: ['kedarkantha-summit', 'juda-ka-talab', 'sankri-village'],
    accommodation: { budget: '₹300–800/night (homestays at Sankri)', mid: '₹800–2,000/night (guesthouses)', luxury: 'N/A — trek camping' },
    weather: [
      { season: 'summer', months: 'May–Jun', temp_min: 5, temp_max: 18, rainfall: 'Moderate', road_conditions: 'Good', crowd_level: 'medium', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 5, temp_max: 12, rainfall: 'Very heavy', road_conditions: 'Dangerous', crowd_level: 'low', accessible: false },
      { season: 'winter', months: 'Dec–Apr', temp_min: -15, temp_max: 5, rainfall: '4–6 ft snow', road_conditions: 'Snow trek', crowd_level: 'high', accessible: true },
      { season: 'snowfall', months: 'Dec–Feb', temp_min: -20, temp_max: -2, rainfall: 'Heavy snow', road_conditions: 'Full snow', crowd_level: 'high', accessible: true },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // KUMAON CIRCUIT
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: 'Mukteshwar',
    slug: 'mukteshwar',
    circuit: 'kumaon-circuit',
    district: 'Nainital',
    coords: { lat: 29.4727, lng: 79.6493 },
    altitude_m: 2286,
    description: 'Mukteshwar is a quiet hilltop town in the Kumaon hills, known for its 350-year-old Shiva temple perched on a cliff edge, sprawling fruit orchards, and unobstructed views of the Himalayan range. It\'s an ideal escape for those seeking peace away from the crowded Nainital circuit.',
    why_visit: [
      'Ancient Mukteshwar Dham temple on a dramatic cliff',
      'Chauli Ki Jali rock formations for rappelling',
      'Panoramic views of Nanda Devi and Trishul ranges',
      'IVRI campus heritage walks and orchards',
      'Perfect for writers, couples, and remote workers',
    ],
    image: '/images/pseo/destinations/mukteshwar.jpg',
    best_months: 'March to June, September to November',
    from_delhi: { distance_km: 350, drive_hours: 8, bus: true, train_to: 'Kathgodam' },
    from_dehradun: { distance_km: 330, drive_hours: 9 },
    nearest_airport: 'Pantnagar Airport (95 km)',
    nearest_railway: 'Kathgodam Railway Station (72 km)',
    travel_times: [
      { to: 'binsar', km: 60, hours: 2 },
      { to: 'kausani', km: 120, hours: 4 },
      { to: 'almora', km: 50, hours: 1.5 },
      { to: 'jageshwar', km: 90, hours: 3 },
    ],
    activities: ['temple-visits', 'photography', 'nature-walks', 'stargazing', 'rappelling', 'bird-watching'],
    attractions: ['mukteshwar-dham', 'chauli-ki-jali', 'ivri-campus', 'methodist-church'],
    accommodation: { budget: '₹800–1,500/night (homestays)', mid: '₹2,000–4,000/night (cottages)', luxury: '₹5,000–12,000/night (boutique resorts)' },
    weather: [
      { season: 'summer', months: 'Apr–Jun', temp_min: 12, temp_max: 28, rainfall: 'Low', road_conditions: 'Good', crowd_level: 'high', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 14, temp_max: 22, rainfall: 'Heavy', road_conditions: 'Slippery', crowd_level: 'low', accessible: true },
      { season: 'autumn', months: 'Oct–Nov', temp_min: 5, temp_max: 20, rainfall: 'None', road_conditions: 'Excellent', crowd_level: 'medium', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: -2, temp_max: 12, rainfall: 'Occasional snow', road_conditions: 'Cold but open', crowd_level: 'low', accessible: true },
    ],
  },
  {
    name: 'Kausani',
    slug: 'kausani',
    circuit: 'kumaon-circuit',
    district: 'Bageshwar',
    coords: { lat: 29.8435, lng: 79.6034 },
    altitude_m: 1890,
    description: 'Kausani is a picturesque hill station that Mahatma Gandhi called the Switzerland of India. Perched on a ridge at 1,890m, it offers a 300 km-wide panoramic view of the Himalayan range including Trishul, Nanda Devi, and Panchachuli. Known for its tea gardens, sunrises, and the Anasakti Ashram where Gandhi wrote Anashakti Yoga.',
    why_visit: [
      'Mahatma Gandhi called it the Switzerland of India',
      '300 km panoramic view of Trishul and Nanda Devi peaks',
      'Kausani Tea Estate — one of the highest in India',
      'Anasakti Ashram (Gandhi Ashram) for peace and reflection',
      'Breathtaking sunrises over the Himalayan range',
    ],
    image: '/images/pseo/destinations/kausani.jpg',
    best_months: 'March to May, October to December',
    from_delhi: { distance_km: 410, drive_hours: 10, bus: true, train_to: 'Kathgodam' },
    from_dehradun: { distance_km: 380, drive_hours: 11 },
    nearest_airport: 'Pantnagar Airport (165 km)',
    nearest_railway: 'Kathgodam Railway Station (140 km)',
    travel_times: [
      { to: 'mukteshwar', km: 120, hours: 4 },
      { to: 'binsar', km: 80, hours: 2.5 },
      { to: 'munsiyari', km: 200, hours: 7 },
      { to: 'almora', km: 52, hours: 1.5 },
      { to: 'jageshwar', km: 60, hours: 2 },
    ],
    activities: ['photography', 'nature-walks', 'temple-visits', 'tea-garden-tours', 'stargazing', 'heritage-walks'],
    attractions: ['anasakti-ashram', 'kausani-tea-estate', 'rudradhari-falls', 'baijnath-temple', 'pant-museum'],
    accommodation: { budget: '₹600–1,500/night (guesthouses)', mid: '₹1,500–4,000/night (hotels)', luxury: '₹4,500–10,000/night (resorts)' },
    weather: [
      { season: 'summer', months: 'Apr–Jun', temp_min: 10, temp_max: 27, rainfall: 'Low', road_conditions: 'Good', crowd_level: 'high', accessible: true },
      { season: 'monsoon', months: 'Jul–Sep', temp_min: 12, temp_max: 22, rainfall: 'Heavy', road_conditions: 'Slippery', crowd_level: 'low', accessible: true },
      { season: 'autumn', months: 'Oct–Nov', temp_min: 5, temp_max: 20, rainfall: 'None', road_conditions: 'Excellent', crowd_level: 'medium', accessible: true },
      { season: 'winter', months: 'Dec–Mar', temp_min: -1, temp_max: 12, rainfall: 'Occasional snow', road_conditions: 'Cold but open', crowd_level: 'low', accessible: true },
    ],
  },
];
