// scripts/pseo/seeds/intents.ts — Intent templates for search-query-targeted pages
import type { IntentTemplate } from '@/types/pseo';

const CURRENT_YEAR = new Date().getFullYear();

export const INTENT_TEMPLATES: IntentTemplate[] = [
  {
    category: 'best_time',
    slug_pattern: 'best-time-to-visit-{target}',
    title_pattern: `Best Time to Visit {Target} (${CURRENT_YEAR}) — Month-by-Month Travel Guide`,
    meta_pattern: `Planning a trip to {Target}? Discover the best time to visit based on weather, crowds, and activities. Complete month-by-month breakdown with insider tips.`,
    target_intent: 'best time to visit {target}',
    applicable_to: ['destination', 'circuit'],
    min_words: 1000,
  },
  {
    category: 'budget_trip',
    slug_pattern: '{target}-budget-trip-under-5000',
    title_pattern: `{Target} Budget Trip Under ₹5,000 (${CURRENT_YEAR}) — Complete Backpacker Guide`,
    meta_pattern: `Explore {Target} on a budget under ₹5,000 with this complete guide. Day-by-day budget breakdown covering transport, stay, food, and activities.`,
    target_intent: '{target} trip under 5000',
    applicable_to: ['circuit', 'destination'],
    min_words: 1200,
  },
  {
    category: 'weekend_trip',
    slug_pattern: 'weekend-trip-from-delhi-to-{target}',
    title_pattern: `Weekend Trip from Delhi to {Target} — 2-Day Itinerary, Route & Costs (${CURRENT_YEAR})`,
    meta_pattern: `Plan a perfect weekend getaway from Delhi to {Target}. Detailed 2-day itinerary with driving route, overnight stay options, activities, and total budget.`,
    target_intent: 'weekend trip from delhi to {target}',
    applicable_to: ['destination'],
    min_words: 1000,
  },
  {
    category: 'how_to_reach',
    slug_pattern: 'how-to-reach-{target}',
    title_pattern: `How to Reach {Target} — By Air, Train & Road (${CURRENT_YEAR} Updated)`,
    meta_pattern: `Complete travel guide to reaching {Target} from Delhi and major cities. Nearest airport, railway station, bus routes, road conditions, and self-drive tips.`,
    target_intent: 'how to reach {target}',
    applicable_to: ['destination'],
    min_words: 800,
  },
  {
    category: 'hidden_places',
    slug_pattern: 'hidden-places-in-{target}',
    title_pattern: `12 Hidden Places in {Target} Most Tourists Miss (${CURRENT_YEAR})`,
    meta_pattern: `Discover offbeat, hidden gems in {Target} that most tourists overlook. Secret viewpoints, lesser-known trails, and untouched villages for the real explorer.`,
    target_intent: 'hidden places in {target}',
    applicable_to: ['circuit'],
    min_words: 1200,
  },
  {
    category: 'couple_trip',
    slug_pattern: '{target}-couple-trip-itinerary',
    title_pattern: `{Target} Couple Trip — Romantic {Duration} Itinerary & Best Stays (${CURRENT_YEAR})`,
    meta_pattern: `Plan the perfect romantic getaway to {Target}. Curated couple-friendly itinerary with cozy stays, sunset viewpoints, and candlelit dining recommendations.`,
    target_intent: '{target} couple trip',
    applicable_to: ['circuit', 'destination'],
    min_words: 1000,
  },
  {
    category: 'adventure',
    slug_pattern: '{target}-adventure-trip-guide',
    title_pattern: `{Target} Adventure Trip — Top Activities, Best Time & Complete Guide (${CURRENT_YEAR})`,
    meta_pattern: `Adrenaline junkie? Here's your complete adventure guide to {Target} covering the best activities, difficulty levels, costs, and safety tips.`,
    target_intent: '{target} adventure activities',
    applicable_to: ['circuit', 'destination'],
    min_words: 1000,
  },
  {
    category: 'family_trip',
    slug_pattern: '{target}-family-trip-plan',
    title_pattern: `{Target} Family Trip Plan — Kid-Friendly {Duration} Itinerary (${CURRENT_YEAR})`,
    meta_pattern: `Planning a family vacation to {Target}? Safe, kid-friendly itinerary with comfortable stays, easy activities, and practical tips for traveling with children.`,
    target_intent: '{target} family trip plan',
    applicable_to: ['circuit', 'destination'],
    min_words: 1000,
  },
  {
    category: 'things_to_do',
    slug_pattern: 'things-to-do-in-{target}',
    title_pattern: `15 Best Things to Do in {Target} (${CURRENT_YEAR}) — Activities, Sightseeing & More`,
    meta_pattern: `Comprehensive guide to the best things to do in {Target}. From adventure sports and temple visits to nature walks and local food — everything you need to know.`,
    target_intent: 'things to do in {target}',
    applicable_to: ['destination', 'circuit'],
    min_words: 1200,
  },
  {
    category: 'travel_tips',
    slug_pattern: '{target}-travel-tips',
    title_pattern: `{Target} Travel Tips — 20 Things to Know Before You Go (${CURRENT_YEAR})`,
    meta_pattern: `Essential travel tips for {Target}. Packing advice, budget hacks, safety precautions, local customs, and practical know-how from experienced travelers.`,
    target_intent: '{target} travel tips',
    applicable_to: ['destination', 'circuit'],
    min_words: 1000,
  },
];
